### ISSUE TITLE
Question about ErrorController

### ISSUE THREAD

**Issue by michaldo** [alimate/errors-spring-boot-starter#107]
In article https://dzone.com/articles/rest-api-error-handling-with-spring-boot you wrote:

> Even if we decide to handle all exceptions using a custom @ExceptionHandler, some exceptions will still manage to escape that handler and the ErrorController would be responsible for exception handling

`errors-spring-boot-starter` use @ExceptionHandler. What about exceptions which escaped to ErrorController?

**Comment by alimate** [comment]
Some exceptions are out of the scope of Spring MVC. Therefore, Spring MVC related abstractions may fail to handle them. 
For instance, Spring Security has its own set of filters. Each filter applies some sort of security-related logic. If something goes wrong, their `ExceptionTranslationFilter` would translate the error to 401 or 403 HTTP errors and write that thing to the response body. Since the filter commits its change to the response, then Spring MVC has no chance to find the error and handle it.
So if you're using plain Spring stuff, in addition to `ExceptionHandler`s, you have to register custom `AccessDeniedHandler`s to handle those sort of exceptions.
With this library, we have `WebErrorHandlers` facilty which finds all registered `WebErrorHandler`s. Also, we catch exceptions from different sources and pass them to `WebErrorHandlers`. Here are the sources:
 - https://github.com/alimate/errors-spring-boot-starter/blob/master/src/main/java/me/alidg/errors/mvc/ErrorsControllerAdvice.java
 - https://github.com/alimate/errors-spring-boot-starter/blob/master/src/main/java/me/alidg/errors/adapter/attributes/ServletErrorAttributes.java
 - https://github.com/alimate/errors-spring-boot-starter/blob/master/src/main/java/me/alidg/errors/adapter/attributes/ReactiveErrorAttributes.java
- https://github.com/alimate/errors-spring-boot-starter/blob/master/src/main/java/me/alidg/errors/conf/ServletSecurityErrorsAutoConfiguration.java

**Comment by michaldo** [comment]
thank for explanation
