### ISSUE TITLE
@SpringBootTest and @AutoConfigureMockMvc  errors  not mocked

### ISSUE THREAD

**Issue by kingour** [alimate/errors-spring-boot-starter#79]
Errors are not mocked in this code:
```java
@AutoConfigureErrors
@SpringBootTest(classes = Application.class)
@TestExecutionListeners(listeners = MockitoTestExecutionListener.class)
@AutoConfigureMockMvc
public class MockBaseTests extends AbstractTestNGSpringContextTests {

    protected static final Logger logger = LoggerFactory.getLogger(MockBaseTests.class);

    @Autowired
    protected MockMvc mockMvc;

    @Test
    public void loadContexts() {
        logger.info("Mock base tests is loading");
    }

    @Test
    public void testNotFound() throws Exception {
//no path /404       
mockMvc.perform(get("/404").contentType(MediaType.APPLICATION_JSON_UTF8)).andExpect(status().isNotFound())
               .andDo(print());
    }

}
```

**Comment by alimate** [comment]
Hi @kingour, Let's take a step back and clarify the intention behind this test:
 1. What you were trying to achieve?  
 2. What did you expect to see?
 3. What's the unexpected result?

Just a few points :
 - `@SpringBootTest` will run your Spring Boot application as a whole, so there is no need for `@AutoConfigureErrors`.
 - As far as I know, the support for `MockBean` is enabled by default, so the `@TestExecutionListeners(listeners = MockitoTestExecutionListener.class)` seems superfluous, too.

I ran this test using JUnit 4 and both tests were passed.

**Comment by kingour** [comment]
no，error message in body not return，only return http status
```
MockHttpServletRequest:
      HTTP Method = GET
      Request URI = /404
       Parameters = {}
          Headers = [Content-Type:"application/json;charset=UTF-8"]
             Body = null
    Session Attrs = {}

Handler:
             Type = org.springframework.web.servlet.resource.ResourceHttpRequestHandler

Async:
    Async started = false
     Async result = null

Resolved Exception:
             Type = null

ModelAndView:
        View name = null
             View = null
            Model = null

FlashMap:
       Attributes = null

MockHttpServletResponse:
           Status = 404
    Error message = null
          Headers = []
     Content type = null
             Body = 
    Forwarded URL = null
   Redirected URL = null
          Cookies = []
```

**Comment by alimate** [comment]
@kingour I see. This happens only in tests and only for a few peculiar exceptions like not found or access denied. Why is that? **That's because, for the Servlet stack, Spring Boot handles errors by redirecting the current request to an `ErrorController`.**
Since `MockMvc` won't follow redirections, then our custom error handler won't get a chance to handle errors. Hence the empty body.

This is a Spring Boot and Spring MVC related issue and we can't do anything about it! You can follow up the real cause:
 - https://github.com/spring-projects/spring-boot/issues/5574
 - https://github.com/spring-projects/spring-boot/issues/7321

This is what @rstoyanchev [said](https://github.com/spring-projects/spring-boot/issues/7321#issuecomment-261343803) about this issue:

> Spring Boot's error handling is based on Servlet container error mappings that result in an ERROR dispatch to an ErrorController. MockMvc however is container-less testing so with no Servlet container the exception simply bubbles up with nothing to stop it.
> 
> So MockMvc tests simply aren't enough to test error responses generated through Spring Boot. I would argue that you shouldn't be testing Spring Boot's error handling. If you're customizing it in any way you can write Spring Boot integration tests (with an actual container) to verify error responses. And then for MockMvc tests focus on fully testing the web layer while expecting exceptions to bubble up.
> 
> This is a typical unit vs integration tests trade off. You do unit tests even if they don't test everything because they give you more control and run faster.

Also, a [neat solution](https://github.com/spring-projects/spring-boot/issues/7321#issuecomment-261498726) from @wilkinsona:

>  If you really want to test the precise format of the error response then you can use an integration test using @SpringBootTest configured with a DEFINED_PORT or RANDOM_PORT web environment and TestRestTemplate.

**Comment by kingour** [comment]
@alimate thx, i got it
